import { mkdir, writeFile, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { profile as p, projects } from '../src/content.mjs';
import { resumeContent as cv } from '../src/resume.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const out = path.join(root, 'dist');
const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const svg = (body, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const icons = {
  telegram: svg('<path d="m21 3-4 18-6-6-4 4v-7L21 3 3 10l4 2m0 0 10-6-6 9"/>'),
  channel: svg('<path d="M4 10h4l11-5v14L8 14H4Z"/><path d="m6 14 2 6h3l-2-6M22 9v6"/>'),
  home: svg('<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>'),
  resume: svg('<path d="M14 2H5v20h14V7Z"/><path d="M14 2v5h5M8 12h8M8 16h6"/>'),
  projects: svg('<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>'),
  links: svg('<path d="m10 13 4-4M8 16l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 1 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(1 1)"/>'),
  meet: svg('<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18m-12 5 2 2 4-4"/>'),
  github: svg('<path d="M9 19c-4.3 1.3-4.3-2-6-2m12 5v-3.4c0-1 .1-1.4-.5-2 3.4-.4 7-1.7 7-7.3A5.7 5.7 0 0 0 20 5.4 5.3 5.3 0 0 0 19.9 1S18.6.6 15.5 2.6a15 15 0 0 0-8 0C4.4.6 3.1 1 3.1 1A5.3 5.3 0 0 0 3 5.4 5.7 5.7 0 0 0 1.5 9.3C1.5 14.9 5.1 16.2 8.5 16.6c-.5.5-.5 1.1-.5 2V22" transform="translate(1 0) scale(.95)"/>'),
  arrow: svg('<path d="M5 12h14m-5-5 5 5-5 5"/>'),
  external: svg('<path d="M7 17 17 7M7 7h10v10"/>'),
  pin: svg('<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>'),
  pause: svg('<path d="M9 6v12M15 6v12"/>'),
  play: svg('<path d="m8 5 11 7-11 7Z"/>'),
};
const routes = [ ['home','/','Главная'], ['resume','/resume/','Резюме'], ['projects','/projects/','Проекты'], ['links','/links/','Ссылки'], ['meet','/meet/','Встреча'] ];
const button = (href, text, secondary=false) => `<a class="button ${secondary?'button-secondary':''}" href="${escape(href)}">${text}${icons.arrow}</a>`;
const tag = text => `<span class="tag">${escape(text)}</span>`;
function art(type) {
  const base = '<defs><pattern id="grid-'+type+'" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#455052" opacity=".5"/></pattern></defs><rect width="360" height="180" fill="url(#grid-'+type+')"/>';
  const cluster = '<g stroke="#426267" fill="none"><path d="M180 56v27M180 83H86v27M180 83h94v27M180 83v27"/><path class="signal" d="M180 56v27h94v27"/></g><g fill="#171d1e" stroke="#446065"><rect x="137" y="25" width="86" height="32" rx="6"/><rect x="54" y="110" width="64" height="35" rx="6"/><rect x="148" y="110" width="64" height="35" rx="6"/><rect x="242" y="110" width="64" height="35" rx="6"/></g><g fill="#e0e6e7" font-size="10" text-anchor="middle"><text x="180" y="45">CONTROL PLANE</text><text x="86" y="131">NODE 01</text><text x="180" y="131">NODE 02</text><text x="274" y="131">NODE 03</text></g><circle class="node-pulse" cx="180" cy="83" r="3" fill="#00eeff"/>';
  const pipeline = '<g stroke="#426267" fill="none"><path d="M77 88h208"/><path class="signal" d="M77 88h208"/></g><g fill="#171d1e" stroke="#446065"><rect x="34" y="61" width="76" height="54" rx="7"/><rect x="142" y="61" width="76" height="54" rx="7"/><rect x="250" y="61" width="76" height="54" rx="7"/></g><g fill="#dce8e9" font-size="10" text-anchor="middle"><text x="72" y="93">COMMIT</text><text x="180" y="93">RUNNER</text><text x="288" y="93">BUILD</text></g><g fill="#00eeff"><circle class="node-pulse" cx="126" cy="88" r="3"/><circle cx="234" cy="88" r="3"/></g>';
  const quorum = '<path d="m100 122 80-85 80 85Z" stroke="#426267" fill="none"/><g fill="#171d1e" stroke="#446065"><circle cx="180" cy="37" r="20"/><circle cx="100" cy="122" r="20"/><circle cx="260" cy="122" r="20"/></g><g fill="#00eeff"><circle cx="180" cy="37" r="4"/><circle cx="100" cy="122" r="4"/><circle class="node-pulse" cx="260" cy="122" r="4"/></g><text x="180" y="107" text-anchor="middle" fill="#dce8e9" font-size="10">QUORUM</text>';
  return `<div class="project-art"><svg viewBox="0 0 360 180" fill="none" aria-hidden="true">${base}${{cluster,pipeline,quorum}[type]}</svg></div>`;
}
function projectCard(project) {
  return `<article class="project-card reveal" data-category="${escape(project.category)}">${art(project.art)}<div class="project-body"><div class="project-meta"><span>${project.category}</span><span>/${project.code}</span></div><h3><a href="${p.github}/${project.slug}" target="_blank" rel="noopener noreferrer">${project.title}${icons.external}</a></h3><p>${project.description}</p><div class="tags">${project.tags.map(tag).join('')}</div><a class="project-source" href="${p.github}/${project.slug}" target="_blank" rel="noopener noreferrer">${icons.github}Открыть код${icons.external}</a></div></article>`;
}
const sectionHead = (label, title, trailing='') => `<div class="section-head"><div><p class="eyebrow">${label}</p><h2>${title}</h2></div>${trailing}</div>`;
const role = `<a class="role-row reveal" href="${p.github}" target="_blank" rel="noopener noreferrer"><span class="company-mark" aria-hidden="true">R</span><span class="role-details"><strong>RWB</strong><span>SRE Team Lead</span></span><span class="role-now">Сейчас</span>${icons.external}</a>`;
const meetingText = p.bookingUrl ? 'Свободные слоты и подтверждение встречи — в Cal.com.' : 'Онлайн-запись скоро появится. Сейчас календарь ещё не открыт.';
function home() { return `<section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow hero-kicker"><span class="tiny-line"></span>ПЕРСОНАЛЬНЫЙ САЙТ</p><h1 id="hero-title"><span class="headline-reveal">Привет, я</span><br><span class="headline-reveal name">Максим<span class="accent">.</span></span></h1><p class="hero-description">SRE Team Lead в <strong>RWB</strong>.<br>Инфраструктура. Надёжность. Практика.</p><div class="hero-actions">${button('/projects/','Мои проекты')}${button('/meet/','Встретиться',true)}</div></div><div class="hero-visual" aria-hidden="true"><canvas id="sphere"></canvas><div class="avatar-frame"><img src="/assets/avatar.png" width="116" height="116" alt="" fetchpriority="high"></div><span class="visual-caption">FADEINFLAMES</span><span class="cross cross-a">+</span><span class="cross cross-b">+</span></div></section>
  <section class="section about reveal">${sectionHead('01 / ОБО МНЕ','Максим Гусев')}<p class="body-large">Руковожу командой SRE в RWB и выстраиваю процессы с нуля: управление инцидентами, наблюдаемость, дежурства и автоматизацию операционной работы.</p><p class="muted">Преподаю в программах Яндекса, ИТМО и Слёрма. Член программных комитетов DevOops и PerfConf.</p></section>
  <section class="section reveal">${sectionHead('02 / СЕЙЧАС','Чем занимаюсь',`<a class="text-link" href="/resume/">К резюме${icons.arrow}</a>`)}${role}<div class="focus-line"><span>В публичных проектах</span><div class="tags">${['Kubernetes','Docker','GitLab CI','Helm','Corosync'].map(tag).join('')}</div></div></section>
  <section class="section">${sectionHead('03 / ПРОЕКТЫ','Из открытого',`<a class="text-link" href="/projects/">Все проекты${icons.arrow}</a>`)}<div class="project-grid">${projects.slice(0,2).map(projectCard).join('')}</div></section>
  <section class="contact-strip reveal"><div><p class="eyebrow">04 / НА СВЯЗИ</p><h2>Продолжим разговор<span class="accent">?</span></h2><p>Ссылки и запись на встречу — в одном месте.</p></div><a class="circle-link" href="/links/" aria-label="Открыть все ссылки">${icons.arrow}</a></section>`; }
function resumeJob(job) {
  return `<article class="resume-job reveal"><div class="resume-job-heading"><h3>${escape(job.company)}</h3><p class="resume-period">${escape(job.period)}</p></div><p class="resume-role">${escape(job.title)}</p>${job.note ? `<p class="resume-note">${escape(job.note)}</p>` : ''}<ul class="resume-points">${job.points.map(point => `<li>${escape(point)}</li>`).join('')}</ul></article>`;
}
function resume() { return `<section class="page-heading resume-heading reveal"><p class="eyebrow">РЕЗЮМЕ</p><h1>Максим Гусев<span class="accent">.</span></h1><p>${escape(p.role)} · Москва</p><div class="resume-actions">${button(p.telegram,'Написать в Telegram')}${button('/meet/','Встретиться',true)}</div></section>
  <div class="resume-intro reveal">${cv.summary.map(text => `<p>${escape(text)}</p>`).join('')}</div>
  <div class="resume-highlights reveal" aria-label="Результаты работы"><div><strong>5–7 мин</strong><p>От сигнала до запуска реагирования в RWB. Ранее — 2–3 часа.</p></div><div><strong>25 → 160</strong><p>Рост количества настроенных алертов в RWB.</p></div><div><strong>−90%</strong><p>Time-to-market за год в РТК-Солар.</p></div></div>
  <nav class="resume-nav" aria-label="Разделы резюме"><a href="#experience">Опыт</a><a href="#teaching">Преподавание</a><a href="#community">Сообщество</a><a href="#skills">Компетенции</a></nav>
  <section class="section resume-section" id="experience">${sectionHead('01 / КАРЬЕРА','Опыт работы')}<div class="resume-timeline">${cv.experience.map(resumeJob).join('')}</div></section>
  <section class="section resume-section">${sectionHead('02 / ПРОЕКТЫ','Проектная работа')}${resumeJob(cv.contract)}</section>
  <section class="section resume-section" id="teaching">${sectionHead('03 / ОБУЧЕНИЕ','Преподавание')}<div class="resume-teaching">${cv.teaching.map(item => `<article class="resume-course reveal"><h3>${escape(item.organization)}</h3><p>${escape(item.description)}</p><div class="resume-course-links">${item.links.map(link => `<a href="${escape(link.url)}" target="_blank" rel="noopener noreferrer">${escape(link.label)}${icons.external}</a>`).join('')}</div></article>`).join('')}</div></section>
  <section class="section resume-section" id="community">${sectionHead('04 / СООБЩЕСТВО','Программные комитеты и выступления')}<div class="resume-community">${cv.community.map(item => `<article class="reveal"><h3>${item.url ? `<a href="${escape(item.url)}" target="_blank" rel="noopener noreferrer">${escape(item.title)}${icons.external}</a>` : escape(item.title)}</h3>${item.description ? `<p>${escape(item.description)}</p>` : ''}</article>`).join('')}</div></section>
  <section class="section resume-section" id="skills">${sectionHead('05 / ПРАКТИКА','Основной стек')}<dl class="resume-skills">${cv.skills.map(skill => `<div><dt>${escape(skill.label)}</dt><dd>${skill.items.map(escape).join(' · ')}</dd></div>`).join('')}</dl><p class="resume-languages">${escape(cv.languages)}</p></section>
  <section class="contact-strip reveal"><div><p class="eyebrow">НА СВЯЗИ</p><h2>Обсудим задачу<span class="accent">?</span></h2><p>Напиши в Telegram или выбери время для встречи.</p></div><a class="circle-link" href="/meet/" aria-label="Записаться на встречу">${icons.arrow}</a></section>`; }
function projectPage() { return `<section class="page-heading reveal"><p class="eyebrow">КОД И ПРАКТИКА</p><h1>Мои проекты<span class="accent">.</span></h1><p>Открытые репозитории, конфигурации и учебные материалы.</p></section><div class="filters" role="group" aria-label="Категория проектов"><button class="filter active" data-filter="all" aria-pressed="true">Все <span>3</span></button><button class="filter" data-filter="Инфраструктура" aria-pressed="false">Инфраструктура</button><button class="filter" data-filter="Обучение" aria-pressed="false">Обучение</button></div><p class="sr-only" id="filter-status" role="status" aria-live="polite"></p><div class="project-grid all-projects">${projects.map(projectCard).join('')}</div><div class="page-next"><a class="text-link" href="${p.github}?tab=repositories" target="_blank" rel="noopener noreferrer">Все репозитории на GitHub${icons.external}</a></div>`; }
function linkRow(icon, title, description, href, external=false) { return `<a class="link-row reveal" href="${escape(href)}"${external?' target="_blank" rel="noopener noreferrer"':''}><span class="link-icon">${icons[icon]}</span><span><strong>${title}</strong><small>${description}</small></span>${external?icons.external:icons.arrow}</a>`; }
function links() { return `<section class="link-profile reveal"><img class="link-avatar" src="/assets/avatar.png" width="84" height="84" alt="Аватар Максима Гусева"><p class="eyebrow">@FADEINFLAMES</p><h1>Давай на связи<span class="accent">.</span></h1><p>Максим Гусев · SRE Team Lead в RWB</p></section><div class="link-list">${linkRow('telegram','Написать в Telegram','Личный контакт · @fadeinflames',p.telegram,true)}${linkRow('channel','Мой Telegram-канал','Заметки · @youngmaxnotes',p.telegramChannel,true)}${linkRow('github','GitHub','Код, репозитории и открытые проекты',p.github,true)}${linkRow('projects','Мои проекты','Инфраструктура и практические материалы','/projects/')}${linkRow('resume','Резюме','Профессиональный профиль','/resume/')}${linkRow('meet','Встреча',p.bookingUrl?'Выбрать время в календаре':'Онлайн-запись скоро появится','/meet/')}</div><div class="share-line"><button class="text-link" id="copy-profile">${icons.links}<span>Скопировать ссылку на эту страницу</span></button><p class="copy-status" id="copy-status" role="status" aria-live="polite"></p></div>`; }
function meet() { return `<section class="page-heading reveal"><p class="eyebrow">ЛИЧНЫЙ КОНТАКТ</p><h1>Встретимся<span class="accent">?</span></h1><p>Место для разговора.</p></section><section class="meeting-card reveal"><div class="meeting-person"><img src="/assets/avatar.png" alt="" width="60" height="60"><div><strong>Максим Гусев</strong><span>SRE Team Lead · RWB</span></div></div><div class="meeting-body"><span class="meeting-icon">${icons.meet}</span><h2>${p.bookingUrl?'Выбери удобное время':'Скоро здесь будет календарь'}</h2><p>${meetingText}</p><span class="timezone">${icons.pin}Москва · UTC+3</span>${p.bookingUrl ? button(p.bookingUrl,'Выбрать время') : '<p class="status-label">Запись пока недоступна</p>'}</div></section><div class="page-next"><a class="text-link" href="/links/">Все ссылки${icons.arrow}</a></div>`; }
const pageContent = { home, resume, projects:projectPage, links, meet };
for (const [key, url, label] of routes) {
  const title = key==='home' ? `${p.name} — SRE Team Lead` : `${label} — ${p.name}`;
  const nav = routes.map(([id,href,name]) => `<a class="dock-link ${id===key?'is-current':''}" href="${href}" aria-label="${name}"${id===key?' aria-current="page"':''}>${icons[id]}<span class="dock-tooltip">${name}</span></a>`).join('');
  const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#111111"><meta name="description" content="Максим Гусев — SRE Team Lead в RWB. Проекты, профессиональный профиль и ссылки."><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="Инфраструктура. Надёжность. Практика."><title>${escape(title)}</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css"><script type="module" src="/assets/app.js"></script></head><body data-page="${key}"><a class="skip-link" href="#main">К содержимому</a><div class="ambient" aria-hidden="true"></div><div class="site-shell"><header class="site-header"><a class="wordmark" href="/" aria-label="Максим Гусев — главная"><span class="brand-mark" aria-hidden="true">f<span>.</span></span><span>fadeinflames<span class="cursor">_</span></span></a><span class="location">${icons.pin}Москва <span class="location-divider">/</span> UTC+3</span></header><main id="main">${pageContent[key]()}</main><footer class="footer"><span>© 2026 Максим Гусев</span><a href="${p.github}" target="_blank" rel="noopener noreferrer">@fadeinflames${icons.external}</a></footer></div><nav class="dock" aria-label="Основная навигация">${nav}<span class="dock-divider"></span><a class="dock-link" href="${p.github}" target="_blank" rel="noopener noreferrer" aria-label="GitHub">${icons.github}<span class="dock-tooltip">GitHub</span></a><button class="dock-link" id="motion-toggle" aria-label="Остановить анимацию" aria-pressed="false"><span class="pause-icon">${icons.pause}</span><span class="play-icon" hidden>${icons.play}</span><span class="dock-tooltip" id="motion-tip">Анимация</span></button></nav></body></html>`;
  const directory = path.join(out, url);
  await mkdir(directory,{recursive:true});
  await writeFile(path.join(directory,'index.html'),html);
}
await mkdir(path.join(out,'assets'),{recursive:true});
await copyFile(path.join(root,'src','assets','avatar.png'),path.join(out,'assets','avatar.png'));
for (const file of ['style.css','app.js','sphere.js','favicon.svg']) await copyFile(path.join(root,'src',file),path.join(out,'assets',file));
console.log('Built 5 static pages. No runtime dependencies.');
