export const profile = {
  name: 'Максим Гусев',
  username: 'fadeinflames',
  role: 'SRE Team Lead',
  company: 'RWB',
  location: 'Москва',
  github: 'https://github.com/fadeinflames',
  telegram: 'https://t.me/fadeinflames',
  telegramChannel: 'https://t.me/youngmaxnotes',
  bookingUrl: 'https://cal.com/fadeinflames/30min',
};

// Public repositories and a project described by the author in a public post.
// Forks are not presented as original work; demo links are included only when verified.
export const projects = [
  {
    slug: 'game-of-incidents',
    title: 'Game of Incidents',
    description: 'Практика устранения инцидентов на сломанных Linux- и Kubernetes-стендах. Браузерный терминал, автоматическая проверка результата, подсказки и разбор решения.',
    tags: ['SRE', 'Linux', 'Kubernetes', 'Docker'],
    category: 'Практика',
    art: 'incident',
    code: '01',
    href: '/projects/game-of-incidents/',
    sourceUrl: null,
    demoUrl: 'https://game.sresh.ru/',
    featured: true,
  },
  {
    slug: 'team-health',
    title: 'Team Health 1:1',
    description: 'Платформа для работы с командой: встречи 1:1, планы развития, цели, обратная связь и командный пульс в одном процессе.',
    tags: ['Node.js', 'PostgreSQL', 'Team management'],
    category: 'Инструменты',
    art: 'health',
    code: '02',
    href: 'https://github.com/fadeinflames/team-health',
    sourceUrl: 'https://github.com/fadeinflames/team-health',
    demoUrl: null,
    featured: true,
  },
  {
    slug: 'wom-games',
    title: 'Wheel of Misfortune',
    description: 'Сценарные тренировки по реагированию на инциденты: ведущий запускает кейс, игрок выбирает действия, система сохраняет историю решений для разбора.',
    tags: ['Next.js', 'TypeScript', 'PostgreSQL'],
    category: 'Практика',
    art: 'game',
    code: '03',
    href: 'https://github.com/fadeinflames/wom-games',
    sourceUrl: 'https://github.com/fadeinflames/wom-games',
    demoUrl: null,
    featured: false,
  },
  {
    slug: 'sre-book-bot',
    title: 'SRE Learning Bot',
    description: 'Telegram-бот для изучения SRE: короткие уроки, квизы, интервальное повторение и проверка заданий наставником.',
    tags: ['Go', 'Telegram', 'PostgreSQL'],
    category: 'Обучение',
    art: 'book',
    code: '04',
    href: 'https://github.com/fadeinflames/sre-book-bot',
    sourceUrl: 'https://github.com/fadeinflames/sre-book-bot',
    demoUrl: null,
    featured: false,
  },
  {
    slug: 'duty-wb',
    title: 'Duty WB',
    description: 'Веб-приложение для недельной ротации дневных и ночных дежурств с API текущего дежурного.',
    tags: ['Python', 'Docker', 'On-call'],
    category: 'Инструменты',
    art: 'duty',
    code: '05',
    href: 'https://github.com/fadeinflames/duty-wb',
    sourceUrl: 'https://github.com/fadeinflames/duty-wb',
    demoUrl: null,
    featured: false,
  },
  {
    slug: 'yandex-workshop-terraform',
    title: 'Terraform: от кода к инфраструктуре',
    description: 'Воркшоп по созданию и изменению инфраструктуры в Yandex Cloud: виртуальная машина с Nginx, outputs, data sources и lifecycle ресурсов.',
    tags: ['Terraform', 'Yandex Cloud', 'IaC'],
    category: 'Обучение',
    art: 'cluster',
    code: '06',
    href: 'https://github.com/fadeinflames/yandex-workshop-terraform',
    sourceUrl: 'https://github.com/fadeinflames/yandex-workshop-terraform',
    demoUrl: null,
    featured: false,
  },
];
